version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A src.tasks.newsletter.celery_app worker --loglevel=info
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app

  app:
    build:
      context: .
    container_name: app
    command: poetry run python3 main.py
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    depends_on:
      - redis
